server:
  port: 18085

  tomcat:
    accept-count: 1000
    connection-timeout: 30000
    max-connections: 20000

spring:
  profiles:
    active: dev

  application:
    name: paas-tag

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 3
      max-lifetime: 60000
      idle-timeout: 30000
    schema: classpath:schema.sql

  redis:
    lettuce:
      pool:
        max-active: 35
        max-wait: 60000
        max-idle: 20
        min-idle: 1
      shutdown-timeout: 30000

paas:
  tag:
    secret: smartpush-cmgddr
    ftp:
      host: 10.253.43.45
      username: hivedata
      password: qwe123QWE!@#
      port: 21
      filepath: /home/paasuser/data/hiveDataModelingResult
      localpath: /data
      file-extension: txt
      scheduled-cron: 0 */1 * * * *

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    max-size: 200MB
    max-history: 30
    total-size-cap: 10GB

---

spring:
  profiles: dev

  datasource:
    #    url: jdbc:mysql://192.168.16.70:3306/dsp?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://192.168.108.51:3306/paas_tag?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    #    password: Hantele@1234!
    password: 123456

  redis:
    host: 192.168.108.51
    port: 6379

logging:
  level:
    web: TRACE
    org:
      springframework:
        web: TRACE
paas:
  tag:
    ftp:
      host: 192.168.108.51
      username: root
      password: Hantele@1234!
      port: 21
      filepath: /data/ftp
      localpath: /data
      scheduled-cron: 0 */1 * * * *

---

spring:
  profiles: pro

  datasource:
    url: jdbc:mysql://192.168.213.66:3306/paas_tag?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root

  redis:
    host: 192.168.212.236
    port: 26379
    password: wM9oZn&33jgwp&O
