package com.richstonedt.fcjx.dsp.paas.tag.dao;

import com.richstonedt.fcjx.dsp.paas.tag.pojo.po.TagBitmapDO;
import com.richstonedt.fcjx.dsp.paas.tag.pojo.po.TagBitmapDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TagBitmapDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    long countByExample(TagBitmapDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int deleteByExample(TagBitmapDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int deleteByPrimaryKey(String tag);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int insert(TagBitmapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int insertSelective(TagBitmapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    List<TagBitmapDO> selectByExampleWithBLOBs(TagBitmapDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    List<TagBitmapDO> selectByExample(TagBitmapDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    TagBitmapDO selectByPrimaryKey(String tag);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") TagBitmapDO record, @Param("example") TagBitmapDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TagBitmapDO record, @Param("example") TagBitmapDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByExample(@Param("record") TagBitmapDO record, @Param("example") TagBitmapDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByPrimaryKeySelective(TagBitmapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TagBitmapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_bitmaps
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByPrimaryKey(TagBitmapDO record);

    void upsert(TagBitmapDO record);
}