package com.richstonedt.fcjx.dsp.paas.tag.dao;

import com.richstonedt.fcjx.dsp.paas.tag.pojo.po.TagDO;
import com.richstonedt.fcjx.dsp.paas.tag.pojo.po.TagDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    long countByExample(TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int deleteByExample(TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int insert(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int insertSelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    List<TagDO> selectByExample(TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    TagDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") TagDO record, @Param("example") TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByExample(@Param("record") TagDO record, @Param("example") TagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByPrimaryKeySelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Apr 16 15:18:18 CST 2020
     */
    int updateByPrimaryKey(TagDO record);
}