package com.richstonedt.fcjx.dsp.ticket.pojo.po;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table paas_tag_tickets
 */
public class PaasTagTicketDO extends PaasTagTicketDOKey {
    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_tag_tickets.create_time
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_tag_tickets.remark
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   状态：0-已失效，1-有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_tag_tickets.status
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_tag_tickets.update_time
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_tag_tickets.create_time
     *
     * @return the value of paas_tag_tickets.create_time
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_tag_tickets.create_time
     *
     * @param createTime the value for paas_tag_tickets.create_time
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_tag_tickets.remark
     *
     * @return the value of paas_tag_tickets.remark
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_tag_tickets.remark
     *
     * @param remark the value for paas_tag_tickets.remark
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_tag_tickets.status
     *
     * @return the value of paas_tag_tickets.status
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_tag_tickets.status
     *
     * @param status the value for paas_tag_tickets.status
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_tag_tickets.update_time
     *
     * @return the value of paas_tag_tickets.update_time
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_tag_tickets.update_time
     *
     * @param updateTime the value for paas_tag_tickets.update_time
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}