package com.richstonedt.fcjx.dsp.ticket.dao;

import com.richstonedt.fcjx.dsp.ticket.pojo.po.PaasTagTicketDO;
import com.richstonedt.fcjx.dsp.ticket.pojo.po.PaasTagTicketDOExample;
import com.richstonedt.fcjx.dsp.ticket.pojo.po.PaasTagTicketDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaasTagTicketDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    long countByExample(PaasTagTicketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int deleteByExample(PaasTagTicketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int deleteByPrimaryKey(PaasTagTicketDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int insert(PaasTagTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int insertSelective(PaasTagTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    List<PaasTagTicketDO> selectByExample(PaasTagTicketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    PaasTagTicketDO selectByPrimaryKey(PaasTagTicketDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasTagTicketDO record, @Param("example") PaasTagTicketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int updateByExample(@Param("record") PaasTagTicketDO record, @Param("example") PaasTagTicketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int updateByPrimaryKeySelective(PaasTagTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_tag_tickets
     *
     * @mbg.generated Sun Apr 26 16:18:12 CST 2020
     */
    int updateByPrimaryKey(PaasTagTicketDO record);
}